# Generated by Django 6.0.2 on 2026-03-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
