# Generated by Django 6.0.2 on 2026-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parkingslot_is_active_parkingspace_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='cctv_video',
            field=models.FileField(blank=True, null=True, upload_to='parking_space_cctv/'),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='google_map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
