# Generated by Django 6.0.2 on 2026-03-09 08:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_parkingspace_cctv_video_parkingspace_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.40'), max_digits=8),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_booking_payment', 'Pending Booking Payment'), ('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('completed', 'Completed')], default='pending_booking_payment', max_length=40),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
