# Generated by Django 6.0.2 on 2026-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_booking_fee_reservation_booking_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='parking_image',
            field=models.ImageField(blank=True, null=True, upload_to='parking_space_images/'),
        ),
    ]
